### ISSUE TITLE
Unable to run flow 'customer_org'

### ISSUE THREAD

**Issue by almostolmos** [SalesforceFoundation/SAL-CumulusCI#1]
If the flow 'customer_org' is included in the local project, an exception is thrown. 
Exception in task dependencies.sfal:customer_org.install_base.update_dependencies
404 Not Found
Run this command for more information about debugging errors: cci error --help

**Steps to reproduce:**
cmd cci flow run dev_org --org dev

**_cumulusci.yml_** 
```
minimum_cumulusci_version: '3.25.0'
project:
    name: DemoAdvisorLink_2
    package:
        name: DemoAdvisorLink_2
        api_version: '50.0'
    dependencies:
        - github: 'https://github.com/SalesforceFoundation/SAL-CumulusCI'
    git:
        default_branch: 'main'
    source_format: sfdx

tasks:
    robot:
        options:
            suites: robot/DemoAdvisorLink_2/tests
            options:
                outputdir: robot/DemoAdvisorLink_2/results

    robot_testdoc:
        options:
            path: robot/DemoAdvisorLink_2/tests
            output: robot/DemoAdvisorLink_2/doc/DemoAdvisorLink_2_tests.html

    run_tests:
        options:
            required_org_code_coverage_percent: 75
sources:
    sfal:
        github: https://github.com/SalesforceFoundation/SAL-CumulusCI
flows:
    dependencies:
        steps:
            1:
                task: update_dependencies
            3:
                flow: sfal:customer_org
            4:
                flow: sfal:hed_config
            5:
                flow: sfal:hed_portal_setup_blob
            6:
                flow: sfal:hed_data
```
